//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: service/service.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate `Example_MessageServiceClient`, then call methods of this protocol to make API calls.
internal protocol Example_MessageServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Example_MessageServiceClientInterceptorFactoryProtocol? { get }

  func streamUpdates(
    _ request: SwiftProtobuf.Google_Protobuf_Empty,
    callOptions: CallOptions?,
    handler: @escaping (Example_Message) -> Void
  ) -> ServerStreamingCall<SwiftProtobuf.Google_Protobuf_Empty, Example_Message>
}

extension Example_MessageServiceClientProtocol {
  internal var serviceName: String {
    return "example.MessageService"
  }

  /// Server streaming call to StreamUpdates
  ///
  /// - Parameters:
  ///   - request: Request to send to StreamUpdates.
  ///   - callOptions: Call options.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ServerStreamingCall` with futures for the metadata and status.
  internal func streamUpdates(
    _ request: SwiftProtobuf.Google_Protobuf_Empty,
    callOptions: CallOptions? = nil,
    handler: @escaping (Example_Message) -> Void
  ) -> ServerStreamingCall<SwiftProtobuf.Google_Protobuf_Empty, Example_Message> {
    return self.makeServerStreamingCall(
      path: "/example.MessageService/StreamUpdates",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeStreamUpdatesInterceptors() ?? [],
      handler: handler
    )
  }
}

internal protocol Example_MessageServiceClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'streamUpdates'.
  func makeStreamUpdatesInterceptors() -> [ClientInterceptor<SwiftProtobuf.Google_Protobuf_Empty, Example_Message>]
}

internal final class Example_MessageServiceClient: Example_MessageServiceClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Example_MessageServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the example.MessageService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Example_MessageServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// To build a server, implement a class that conforms to this protocol.
internal protocol Example_MessageServiceProvider: CallHandlerProvider {
  var interceptors: Example_MessageServiceServerInterceptorFactoryProtocol? { get }

  func streamUpdates(request: SwiftProtobuf.Google_Protobuf_Empty, context: StreamingResponseCallContext<Example_Message>) -> EventLoopFuture<GRPCStatus>
}

extension Example_MessageServiceProvider {
  internal var serviceName: Substring { return "example.MessageService" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "StreamUpdates":
      return ServerStreamingServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<SwiftProtobuf.Google_Protobuf_Empty>(),
        responseSerializer: ProtobufSerializer<Example_Message>(),
        interceptors: self.interceptors?.makeStreamUpdatesInterceptors() ?? [],
        userFunction: self.streamUpdates(request:context:)
      )

    default:
      return nil
    }
  }
}

internal protocol Example_MessageServiceServerInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when handling 'streamUpdates'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeStreamUpdatesInterceptors() -> [ServerInterceptor<SwiftProtobuf.Google_Protobuf_Empty, Example_Message>]
}
